name: 'CNP-HS8-Backfill-daily'

on:
  workflow_dispatch:
    inputs:
      groupid:
        description: 'download_group_id,from <0> to <xx>,<0> is latest 8 month'
        required: false
        default: "None"
  schedule:
    - cron: '0 18,13 * * *'


env:
  repo_name: CECNdata/GA-sec
  csv: CNP-all-HS8-Backfill.csv
  retry: 6
  cncc_url: http://stats.customs.gov.cn/queryData/queryDataList
  groupid: ${{ github.event.inputs.groupid }}

jobs:
  download:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - line: 0
         - line: 1
         - line: 2
         - line: 3
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
        with:
          repository: '${{ env.repo_name  }}'
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains you PAT
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          cd customs
          python -m pip install --upgrade pip
          pip install fire
          pip install pipreqs
          pipreqs .
          pip install -r requirements.txt
      - name: Install Playwright
        run: |
            npx playwright install-deps webkit
            python -m playwright install webkit
            npx playwright install-deps firefox
            python -m playwright install firefox
      - name: run customs download
        continue-on-error: true
        run: |
            cd feed
            timeout 1800 xvfb-run python download_pyscript/run_backfill_daily.py   --path CNP-Customs-HS8/mapping/${{env.csv}} --line "${{matrix.line}}" --retry ${{env.retry}}
            
